import { CHANNEL_STREAM_UPDATE_INTERVAL_MS } from '../channel-provider.js';

export const SLACK_STREAM_UPDATE_INTERVAL_MS =
  CHANNEL_STREAM_UPDATE_INTERVAL_MS.slack;
export const SLACK_FALLBACK_CHUNK_MAX_LENGTH = 4000;
export const SLACK_NATIVE_APPEND_MAX_LENGTH = 12000;
